/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package internalPages;

import java.awt.Color;
import java.awt.Image;
import javax.swing.ImageIcon;
import myApp.dashBoard;
import myApp.logBoard;
import myApp.scholarPage;
import myApp.studentPage;

/**
 *
 * @author SCC-PC19
 */
public class admin extends javax.swing.JFrame {

    /**
     * Creates new form admin
     */
    public byte[] imageBytes;
    String path;
    String fileName = null;
    String imgPath = null;
    byte[] person_image = null;
    public static String reference;
    public String uname = "";
    public String ads = "";

    public admin() {
        initComponents();

    }

    public ImageIcon ResizeImage(String ImagePath, byte[] pic) {
        ImageIcon MyImage = null;
        if (ImagePath != null) {
            MyImage = new ImageIcon(ImagePath);
        } else {
            MyImage = new ImageIcon(pic);
        }
        Image img = MyImage.getImage();
        Image newImg = img.getScaledInstance(image.getWidth(), image.getHeight(), Image.SCALE_SMOOTH);
        ImageIcon image = new ImageIcon(newImg);
        return image;
    }

    public void displayImage() {

    }
    Color navcolor = new Color(255, 255, 255);
    Color headercolor = new Color(240, 240, 240);
    Color bodycolor = new Color(240, 240, 240);

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        info = new javax.swing.JPanel();
        jPanel15 = new javax.swing.JPanel();
        image = new javax.swing.JLabel();
        acc = new javax.swing.JLabel();
        position = new javax.swing.JLabel();
        studentId = new javax.swing.JTextField();
        email1 = new javax.swing.JLabel();
        user = new javax.swing.JTextField();
        num = new javax.swing.JTextField();
        st = new javax.swing.JLabel();
        accSet = new javax.swing.JPanel();
        manageStudents = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        reports = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        logout = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel33 = new javax.swing.JLabel();
        jLabel34 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);

        jPanel1.setPreferredSize(new java.awt.Dimension(630, 580));
        jPanel1.setLayout(null);

        jPanel2.setBackground(new java.awt.Color(204, 204, 204));
        jPanel2.setPreferredSize(new java.awt.Dimension(530, 600));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        info.setBackground(new java.awt.Color(204, 204, 204));
        info.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        info.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel15.setBackground(new java.awt.Color(255, 255, 255));

        image.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/uuser.png"))); // NOI18N
        image.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                imageMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel15Layout = new javax.swing.GroupLayout(jPanel15);
        jPanel15.setLayout(jPanel15Layout);
        jPanel15Layout.setHorizontalGroup(
            jPanel15Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel15Layout.createSequentialGroup()
                .addContainerGap(16, Short.MAX_VALUE)
                .addComponent(image, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel15Layout.setVerticalGroup(
            jPanel15Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(image, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 150, Short.MAX_VALUE)
        );

        info.add(jPanel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 20, 140, 150));

        acc.setBackground(new java.awt.Color(255, 255, 255));
        acc.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        acc.setText("ACCOUNT ID:");
        info.add(acc, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 50, 110, 30));

        position.setBackground(new java.awt.Color(255, 255, 255));
        position.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        position.setText("Contact :");
        info.add(position, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 140, -1, 30));

        studentId.setEditable(false);
        studentId.setBackground(new java.awt.Color(255, 255, 255));
        studentId.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        info.add(studentId, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 50, 180, 30));

        email1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        email1.setText("USERNAME");
        info.add(email1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 100, 80, 30));

        user.setEditable(false);
        user.setBackground(new java.awt.Color(255, 255, 255));
        user.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        info.add(user, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 100, 180, 30));

        num.setEditable(false);
        num.setBackground(new java.awt.Color(255, 255, 255));
        num.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        info.add(num, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 140, 180, 30));

        st.setBackground(new java.awt.Color(0, 0, 0));
        info.add(st, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 180, 110, 30));

        jPanel2.add(info, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 50, 610, 230));

        accSet.setBackground(new java.awt.Color(204, 204, 204));
        accSet.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        accSet.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        manageStudents.setBackground(new java.awt.Color(255, 255, 255));
        manageStudents.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        manageStudents.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                manageStudentsMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                manageStudentsMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                manageStudentsMouseExited(evt);
            }
        });
        manageStudents.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        manageStudents.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 30, 103, -1));

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel5.setText("MANAGE STUDENTS");
        manageStudents.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 140, 120, 20));

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/edituser.png"))); // NOI18N
        manageStudents.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 20, 100, 110));

        accSet.add(manageStudents, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 40, 170, 170));

        reports.setBackground(new java.awt.Color(255, 255, 255));
        reports.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        reports.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                reportsMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                reportsMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                reportsMouseExited(evt);
            }
        });
        reports.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel6.setText("MANAGE SCHOLARSHIP");
        reports.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 140, 150, 20));

        jLabel10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/reports.png"))); // NOI18N
        reports.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 20, 100, 110));

        accSet.add(reports, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 40, 160, 170));

        logout.setBackground(new java.awt.Color(255, 255, 255));
        logout.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        logout.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                logoutMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                logoutMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                logoutMouseExited(evt);
            }
        });
        logout.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel9.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel9.setText("    LOGOUT");
        logout.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 140, 70, 20));

        jLabel12.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/out.png"))); // NOI18N
        logout.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 20, 100, 110));

        accSet.add(logout, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 40, 180, 170));

        jPanel2.add(accSet, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 290, 610, 250));

        jLabel33.setFont(new java.awt.Font("Tahoma", 0, 48)); // NOI18N
        jLabel33.setText("-");
        jPanel2.add(jLabel33, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 0, -1, 30));

        jLabel34.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel34.setForeground(new java.awt.Color(255, 255, 255));
        jLabel34.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/icons8-close-30.png"))); // NOI18N
        jLabel34.setText(" x");
        jLabel34.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel34MouseClicked(evt);
            }
        });
        jPanel2.add(jLabel34, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 0, 30, -1));

        jLabel1.setBackground(new java.awt.Color(255, 255, 255));
        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel1.setText("ADMIN PAGE");
        jPanel2.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 0, -1, 50));

        jPanel1.add(jPanel2);
        jPanel2.setBounds(0, 0, 630, 550);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 550, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void manageStudentsMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_manageStudentsMouseClicked

        studentPage sp = new studentPage();
        sp.setVisible(true);
        this.setVisible(false);
        sp.uname = uname;
        sp.ad = ads;

        // Assuming you have the image path stored in 'reference'
//        sp.setImage(reference);

    }//GEN-LAST:event_manageStudentsMouseClicked

    private void manageStudentsMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_manageStudentsMouseEntered
        manageStudents.setBackground(navcolor);
    }//GEN-LAST:event_manageStudentsMouseEntered

    private void manageStudentsMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_manageStudentsMouseExited
        manageStudents.setBackground(bodycolor);
    }//GEN-LAST:event_manageStudentsMouseExited

    private void reportsMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_reportsMouseClicked
//        JFrame mainJFrame = (JFrame) SwingUtilities.getWindowAncestor(this);
//        mainJFrame.dispose();
        scholarPage st = new scholarPage();
        st.setVisible(true);
        this.hide();
        st.ads = ads;

    }//GEN-LAST:event_reportsMouseClicked

    private void reportsMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_reportsMouseEntered
        reports.setBackground(navcolor);
    }//GEN-LAST:event_reportsMouseEntered

    private void reportsMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_reportsMouseExited
        reports.setBackground(bodycolor);
    }//GEN-LAST:event_reportsMouseExited

    private void logoutMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_logoutMouseClicked

//        JFrame mainJFrame = (JFrame) SwingUtilities.getWindowAncestor(this);
//        mainJFrame.dispose();
        logBoard lb = new logBoard();
        lb.setVisible(true);
        this.hide();
    }//GEN-LAST:event_logoutMouseClicked

    private void logoutMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_logoutMouseEntered
        logout.setBackground(navcolor);
    }//GEN-LAST:event_logoutMouseEntered

    private void logoutMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_logoutMouseExited
        logout.setBackground(bodycolor);
    }//GEN-LAST:event_logoutMouseExited

    private void jLabel34MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel34MouseClicked

        dashBoard db = new dashBoard();
        db.setVisible(true);
        this.hide();
        db.name = uname;
        db.nam = ads;
    }//GEN-LAST:event_jLabel34MouseClicked

    private void imageMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_imageMouseClicked
        displayImage();
    }//GEN-LAST:event_imageMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(admin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(admin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(admin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(admin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new admin().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel acc;
    private javax.swing.JPanel accSet;
    private javax.swing.JLabel email1;
    public javax.swing.JLabel image;
    private javax.swing.JPanel info;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel33;
    private javax.swing.JLabel jLabel34;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel15;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel logout;
    private javax.swing.JPanel manageStudents;
    public javax.swing.JTextField num;
    private javax.swing.JLabel position;
    private javax.swing.JPanel reports;
    public javax.swing.JLabel st;
    public javax.swing.JTextField studentId;
    public javax.swing.JTextField user;
    // End of variables declaration//GEN-END:variables
}
