/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package internalPages;

import config.dbconnector;
import java.awt.Component;
import java.awt.Font;
import java.awt.print.PrinterException;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.text.MessageFormat;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import javax.swing.RowFilter;
import javax.swing.SwingUtilities;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableModel;
import javax.swing.table.TableRowSorter;
import myApp.applicationForm;
import myApp.dashBoard;
import myApp.editReports;
import myApp.logBoard;
import myApp.printAppForm;
import myApp.updateScholarForm;
import net.proteanit.sql.DbUtils;

/**
 *
 * @author SCC-PC10
 */
public class report extends javax.swing.JFrame {

    /**
     * Creates new form report
     */
    public report() {
        initComponents();
        displayData();
    }
    private Connection connection;
    public static String name = "";
    public String ad = "";

    public void displayData() {

        try {
            dbconnector dbc = new dbconnector();
            ResultSet rs = dbc.getData("SELECT table_student.student_id, \n"
                    + "                    table_student.gmail, \n"
                    + "                    table_student.name, \n"
                    + "                    table_student.student_course, \n"
                    + "                    table_scholarship.scholarship_status ,\n"
                    + "                    table_scholarship.scholarship_name \n"
                    + "                    FROM application_table \n"
                    + "                    LEFT JOIN table_student ON application_table.student_id = table_student.student_id \n"
                    + "                    LEFT JOIN table_scholarship ON application_table.scholarship_id = table_scholarship.scholarship_id");
            report_table.setModel(DbUtils.resultSetToTableModel(rs));

        } catch (SQLException ex) {
            System.out.println("Error Message" + ex);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        report_table = new javax.swing.JTable();
        search = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        print = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        box = new javax.swing.JComboBox<>();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jLabel33 = new javax.swing.JLabel();
        jLabel34 = new javax.swing.JLabel();
        jButton4 = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jButton5 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);

        jPanel2.setBackground(new java.awt.Color(204, 204, 204));
        jPanel2.setPreferredSize(new java.awt.Dimension(630, 580));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        report_table.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                report_tableMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(report_table);

        jPanel2.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 160, 650, 480));

        search.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        search.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                searchActionPerformed(evt);
            }
        });
        jPanel2.add(search, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 110, 160, 40));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("REPORTS");
        jPanel2.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 30, 130, 30));

        print.setFont(new java.awt.Font("Tahoma", 1, 10)); // NOI18N
        print.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/icons8-print-30.png"))); // NOI18N
        print.setText("Table");
        print.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                printActionPerformed(evt);
            }
        });
        jPanel2.add(print, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 110, 110, 40));

        jButton1.setFont(new java.awt.Font("Tahoma", 1, 10)); // NOI18N
        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/icons8-print-30.png"))); // NOI18N
        jButton1.setText("Information");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 110, 130, 40));

        box.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        box.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Filter", "Pending", "Approved", "Declined" }));
        box.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                boxActionPerformed(evt);
            }
        });
        jPanel2.add(box, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 110, 80, 40));

        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/icons8-add-45.png"))); // NOI18N
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 110, 50, 40));

        jButton3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/icons8-refresh-38.png"))); // NOI18N
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 110, 40, 40));

        jLabel33.setFont(new java.awt.Font("Tahoma", 0, 48)); // NOI18N
        jLabel33.setText("-");
        jPanel2.add(jLabel33, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 0, -1, 30));

        jLabel34.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel34.setForeground(new java.awt.Color(255, 255, 255));
        jLabel34.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/icons8-close-30.png"))); // NOI18N
        jLabel34.setText(" x");
        jLabel34.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel34MouseClicked(evt);
            }
        });
        jPanel2.add(jLabel34, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 0, 30, -1));

        jButton4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/icons8-delete-45.png"))); // NOI18N
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton4, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 110, 40, 40));

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/t_1.png"))); // NOI18N
        jPanel2.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        jButton5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/icons8-search-25.png"))); // NOI18N
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton5, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 110, 40, 40));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 670, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 670, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 640, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 640, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void report_tableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_report_tableMouseClicked

//        int rowIndex = report_table.getSelectedRow();
//        if (rowIndex < 0) {
//
//        } else {
//
//            TableModel model = report_table.getModel();
//            printAppForm st = new printAppForm();
//
//            st.id.setText("" + model.getValueAt(rowIndex, 0));
//            st.l.setText("" + model.getValueAt(rowIndex, 1));
//            st.fName.setText("" + model.getValueAt(rowIndex, 2));
//            st.course.setText("" + model.getValueAt(rowIndex, 3));
//            st.status.setText("" + model.getValueAt(rowIndex, 4));
//            st.scholar.setText("" + model.getValueAt(rowIndex, 5));
//            st.ads = ad;
//        }
    }//GEN-LAST:event_report_tableMouseClicked

    private void searchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_searchActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_searchActionPerformed

    private void printActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_printActionPerformed
        MessageFormat header = new MessageFormat("SCHOLAR REPORT");
        MessageFormat footer = new MessageFormat("Scholarship");
        try {
            report_table.print(JTable.PrintMode.FIT_WIDTH, header, footer);
        } catch (PrinterException e) {
            JOptionPane.showMessageDialog(null, "Cannot be print!" + e.getMessage());
        }
    }//GEN-LAST:event_printActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed

        printAppForm rp = new printAppForm();
        int selectedRow = report_table.getSelectedRow();

        if (selectedRow != -1) {
            try {
                DefaultTableModel model = (DefaultTableModel) report_table.getModel();
                int columnCount = model.getColumnCount();
                StringBuilder rowData = new StringBuilder();

                String[] columnHeaders = {"\tStudent ID", "\tGmail", "\tName", "\tStudent Course", "\tScholarship Status", "\tScholarship Name"};
                String[] rowDataValues = new String[columnCount];

                for (int column = 0; column < columnCount; column++) {
                    rowDataValues[column] = model.getValueAt(selectedRow, column).toString();
                }

                String header = "\n\tReport Page\n\n";

                String details = "\tApplication Details:\n\n\n";
                rowData.append(header);
                rowData.append(details);

                for (int i = 0; i < columnHeaders.length; i++) {
                    rowData.append(columnHeaders[i]).append(": ").append(rowDataValues[i]).append("\n");
                    rowData.append("\n");
                }
                rp.setVisible(true);
                rp.print.setText(rowData.toString());
                rp.print.setAlignmentX(Component.CENTER_ALIGNMENT);
                rp.print.setAlignmentY(Component.CENTER_ALIGNMENT);

                Font font = new Font("Tahoma", Font.BOLD, 15);
                rp.print.setFont(font);
                rp.ads = ad;
                //   rp.print.print();

                this.dispose();
                JFrame mainFrame = (JFrame) SwingUtilities.getWindowAncestor(this);
                mainFrame.dispose();

            } catch (Exception e) {
            }

        } else {
            JOptionPane.showMessageDialog(null, "Please select an Item");
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void boxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_boxActionPerformed
        try {
            Connection conn = DriverManager.getConnection("jdbc:mysql://localhost:3306/scholarshipsystem", "root", "");
            PreparedStatement statement = conn.prepareStatement("SELECT table_student.student_id, \n"
                    + "                   table_student.gmail, \n"
                    + "                    table_student.name,\n"
                    + "                    table_student.student_course, \n"
                    + "                    table_scholarship.scholarship_status \n"
                    + "                    FROM application_table \n"
                    + "                    INNER JOIN table_student ON application_table.student_id = table_student.student_id \n"
                    + "                    INNER JOIN table_scholarship ON application_table.scholarship_id =table_scholarship.scholarship_id WHERE scholarship_status = '" + box.getSelectedItem() + "'");

            ResultSet rs = statement.executeQuery();
            report_table.setModel(DbUtils.resultSetToTableModel(rs));

        } catch (SQLException e) {
            System.out.println("Connection Error: " + e);
        }
    }//GEN-LAST:event_boxActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
//        JFrame mainJFrame = (JFrame) SwingUtilities.getWindowAncestor(this);
//        mainJFrame.dispose();
        applicationForm af = new applicationForm();
        //        addStudentForm af = new addStudentForm();
        af.setVisible(true);
        this.hide();
        af.ads = ad;
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed

        displayData();
        report rp = new report();
        rp.setVisible(true);
        rp.ad = ad;
        this.hide();
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jLabel34MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel34MouseClicked

        dashBoard db = new dashBoard();
        db.setVisible(true);
        db.name = name;
        db.nam = ad;
        this.hide();
    }//GEN-LAST:event_jLabel34MouseClicked

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        int rowIndex = report_table.getSelectedRow();

        if (rowIndex < 0) {
            JOptionPane.showMessageDialog(null, "Please select a data first");
        } else {
            TableModel model = report_table.getModel();
            Object value = model.getValueAt(rowIndex, 0);
            String id = value.toString();
            int a = JOptionPane.showConfirmDialog(null, "Are you sure?");
            if (a == JOptionPane.YES_OPTION) {
                dbconnector dbc = new dbconnector();
                dbc.deleteReport(Integer.parseInt(id));
                displayData();

            }

        }
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        DefaultTableModel model = (DefaultTableModel) report_table.getModel();
        TableRowSorter<DefaultTableModel> obj = new TableRowSorter<>(model);
        report_table.setRowSorter(obj);
        obj.setRowFilter(RowFilter.regexFilter(search.getText()));  // TODO add your handling code here:
    }//GEN-LAST:event_jButton5ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(report.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(report.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(report.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(report.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new report().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> box;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel33;
    private javax.swing.JLabel jLabel34;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JButton print;
    public javax.swing.JTable report_table;
    private javax.swing.JTextField search;
    // End of variables declaration//GEN-END:variables
}
