/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package student;

import config.dbconnector;
import internalPages.report;
import java.awt.Image;
import java.awt.image.BufferedImage;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.*;
import java.sql.SQLException;
import javax.imageio.ImageIO;
import javax.swing.ImageIcon;
import javax.swing.JFileChooser;
import javax.swing.filechooser.FileNameExtensionFilter;

;

/**
 *
 * @author Hariell
 */
public class applicationForm extends javax.swing.JFrame {

    /**
     * Creates new form applicationForm
     */
    public String sc_id;
    public int studentID;

    public applicationForm() {
        initComponents();
        loadCombo();
    }

    Connection con;
    public static String name = "";
    public String ads = "";

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        panel = new javax.swing.JPanel();
        jLabel15 = new javax.swing.JLabel();
        lname = new javax.swing.JTextField();
        jButton3 = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jComboBox1 = new javax.swing.JComboBox<>();
        jLabel1 = new javax.swing.JLabel();
        fname = new javax.swing.JTextField();
        jPanel2 = new javax.swing.JPanel();
        display = new javax.swing.JLabel();
        up = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        display1 = new javax.swing.JLabel();
        up1 = new javax.swing.JButton();
        jLabel35 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        panel.setBackground(new java.awt.Color(255, 255, 255));
        panel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel15.setFont(new java.awt.Font("Segoe UI", 1, 20)); // NOI18N
        jLabel15.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel15.setText("APPLICATION FORM");
        panel.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 20, 800, 30));

        lname.setEditable(false);
        lname.setBackground(new java.awt.Color(255, 255, 255));
        lname.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Last name", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 0, 12), new java.awt.Color(102, 102, 102))); // NOI18N
        panel.add(lname, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 70, 140, 50));

        jButton3.setBackground(new java.awt.Color(221, 68, 112));
        jButton3.setForeground(new java.awt.Color(255, 255, 255));
        jButton3.setText("Save");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        panel.add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 430, 140, 40));

        jButton1.setText("Cancel");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        panel.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 430, 140, 40));

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "BSIT", "BSCRIM", "BSED" }));
        panel.add(jComboBox1, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 150, 290, 40));

        jLabel1.setBackground(new java.awt.Color(153, 153, 153));
        jLabel1.setForeground(new java.awt.Color(153, 153, 153));
        jLabel1.setText("2x2 picture *(Required)");
        panel.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 70, 130, -1));

        fname.setEditable(false);
        fname.setBackground(new java.awt.Color(255, 255, 255));
        fname.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "First name", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 0, 12), new java.awt.Color(102, 102, 102))); // NOI18N
        panel.add(fname, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 70, 140, 50));

        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        jPanel2.add(display, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 130, 90));

        panel.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 90, -1, 130));

        up.setText("Import");
        up.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                upActionPerformed(evt);
            }
        });
        panel.add(up, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 230, 130, 30));

        jLabel2.setForeground(new java.awt.Color(153, 153, 153));
        jLabel2.setText("Course");
        panel.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 130, 290, -1));

        jLabel3.setForeground(new java.awt.Color(153, 153, 153));
        jLabel3.setText("Grades *(Reqruied)");
        panel.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 280, 130, -1));

        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        jPanel3.add(display1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 130, 90));

        panel.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 300, -1, 130));

        up1.setText("Import");
        up1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                up1ActionPerformed(evt);
            }
        });
        panel.add(up1, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 440, 130, 30));

        jPanel1.add(panel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 800, 500));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 800, 500));

        jLabel35.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        jLabel35.setForeground(new java.awt.Color(255, 255, 255));
        jLabel35.setText("-");
        getContentPane().add(jLabel35, new org.netbeans.lib.awtextra.AbsoluteConstraints(203, 12, -1, 20));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        try {
            dbconnector dbc = new dbconnector();
            String sql = "INSERT INTO application_table (user_id, scholarship_id, status) VALUES( ?,?, ?)";
            PreparedStatement pst = (PreparedStatement) con.prepareStatement(sql);

            pst.setString(1, (String) idd.getSelectedItem());
            pst.setString(2, scholarID.getText());
            pst.setString(3, status.getText());

            pst.execute();
            report db = new report();
            db.setVisible(true);
            this.hide();
            db.ad = ads;
        } catch (Exception e) {
            System.out.println("" + e);
        }

    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        this.dispose();
        fname.setText("");
        gmail.setText("");
        course.setText("");
        contact.setText("");
        female.setSelected(false);
        male.setSelected(false);
        status.setSelectedIndex(0);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void upActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_upActionPerformed
        JFileChooser fileChooser = new JFileChooser();
        FileNameExtensionFilter filter = new FileNameExtensionFilter("Image Files", "jpg", "jpeg", "png", "gif");
        fileChooser.setFileFilter(filter);

        int result = fileChooser.showOpenDialog(this);

        if (result == JFileChooser.APPROVE_OPTION) {
            selectedFile = fileChooser.getSelectedFile();

            try {
                BufferedImage originalImage = ImageIO.read(selectedFile);

                Image resizedImage = originalImage.getScaledInstance(160, 160, Image.SCALE_SMOOTH);
                ImageIcon icon = new ImageIcon(resizedImage);
                display.setIcon(icon);

                String imageName = selectedFile.getName();
                imagePath = "src/profile_picture/" + imageName;
                File destination = new File(imagePath);
                Files.copy(selectedFile.toPath(), destination.toPath(), StandardCopyOption.REPLACE_EXISTING);
                // Update the selectedFile to point to the new location
                selectedFile = destination;
            } catch (IOException e) {
                e.printStackTrace();
                JOptionPane.showMessageDialog(null, "Error reading image file: " + e.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
            }
        }
    }//GEN-LAST:event_upActionPerformed

    private void up1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_up1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_up1ActionPerformed
    void loadCombo() {

        try {
            con = DriverManager.getConnection("jdbc:mysql://localhost:3306/scholarshipsystem", "root", "");
            dbconnector dbc = new dbconnector();
            ResultSet rs = dbc.getData("SELECT * FROM table_student ");
            ResultSet rst = dbc.getData("SELECT * FROM table_scholarship ");
            while (rs.next()) {
                idd.addItem(rs.getString("student_id"));
            }
            while (rst.next()) {
                scholarshipName.addItem(rst.getString("scholarship_name"));
//
            }

        } catch (SQLException e) {
            System.out.println("" + e);
        }
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(applicationForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(applicationForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(applicationForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(applicationForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new applicationForm().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel display;
    private javax.swing.JLabel display1;
    private javax.swing.JTextField fname;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton3;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel35;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JTextField lname;
    private javax.swing.JPanel panel;
    private javax.swing.JButton up;
    private javax.swing.JButton up1;
    // End of variables declaration//GEN-END:variables
}
