/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package myApp;

import config.dbconnector;
import internalPages.admin;
import javax.swing.JOptionPane;


/**
 *
 * @author Hariell
 */
public class addScholarForm extends javax.swing.JFrame {

    /**
     * Creates new form updateScholarForm
     */
    public static String name = "";
    public String ads = "";

    public addScholarForm() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel34 = new javax.swing.JPanel();
        jLabel33 = new javax.swing.JLabel();
        jLabel34 = new javax.swing.JLabel();
        jPanel20 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        sc_id = new javax.swing.JTextField();
        jLabel28 = new javax.swing.JLabel();
        sc_des = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        scholarName = new javax.swing.JComboBox<>();
        scholarType = new javax.swing.JComboBox<>();
        jButton3 = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);

        jPanel34.setBackground(new java.awt.Color(204, 204, 204));
        jPanel34.setPreferredSize(new java.awt.Dimension(543, 594));
        jPanel34.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel33.setFont(new java.awt.Font("Tahoma", 0, 48)); // NOI18N
        jLabel33.setText("-");
        jPanel34.add(jLabel33, new org.netbeans.lib.awtextra.AbsoluteConstraints(700, 0, -1, 30));

        jLabel34.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel34.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/icons8-close-30.png"))); // NOI18N
        jLabel34.setText(" x");
        jLabel34.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel34MouseClicked(evt);
            }
        });
        jPanel34.add(jLabel34, new org.netbeans.lib.awtextra.AbsoluteConstraints(720, 0, 30, -1));

        jPanel20.setBackground(new java.awt.Color(204, 204, 204));
        jPanel20.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel20.setOpaque(false);
        jPanel20.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel5.setText("Scholarship ID :");
        jPanel20.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 20, -1, 33));

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel6.setText("Scholarship Name:");
        jPanel20.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 60, -1, 20));

        sc_id.setEditable(false);
        sc_id.setBackground(new java.awt.Color(204, 204, 204));
        sc_id.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel20.add(sc_id, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 20, 179, 28));

        jLabel28.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel28.setText("Scholarship Description:");
        jPanel20.add(jLabel28, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 160, 180, 33));
        jPanel20.add(sc_des, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 140, 320, 80));

        jLabel10.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel10.setText("Scholarship Type :");
        jPanel20.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 100, 130, 33));

        scholarName.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "CHED\t", "UNIFAST", "WORKING" }));
        jPanel20.add(scholarName, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 60, 180, 30));

        scholarType.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Academic", "Governments", " " }));
        jPanel20.add(scholarType, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 100, 180, 30));

        jButton3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/icons8-add-45.png"))); // NOI18N
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        jPanel20.add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 230, 100, 40));

        jPanel34.add(jPanel20, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 110, 620, 300));

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/t_1.png"))); // NOI18N
        jPanel34.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 110, 110));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/scclogo.png"))); // NOI18N
        jPanel34.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 240, 390, 370));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel34, javax.swing.GroupLayout.PREFERRED_SIZE, 750, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(29, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel34, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jLabel34MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel34MouseClicked

        admin db = new admin();
        db.setVisible(true);
        this.hide();
        db.ads = ads;
        //int ex = JOptionPane.showConfirmDialog(null, "Confirm Exit!");
        //        if (ex == JOptionPane.YES_OPTION) {
        //            System.exit(ex);
        //        }
    }//GEN-LAST:event_jLabel34MouseClicked
    
    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
         dbconnector dbc = new dbconnector();
        if (sc_des.getText().isEmpty()) {
            JOptionPane.showMessageDialog(null, " All Fields Require!");
        } else {
            dbc.insertData("INSERT INTO table_scholarship (scholarship_name,scholarship_type,scholarship_descrip,scholarship_status) " + "VALUES ("
                    + "'" + scholarName.getSelectedItem() + "',"
                    + " '" + scholarType.getSelectedItem() + "',"
                    + " '" + sc_des.getText() + "',"
                    + "'" + "Pending')");
            scholarPage db = new scholarPage();
            db.setVisible(true);
            this.hide();
            db.ads = ads ;
    }//GEN-LAST:event_jButton3ActionPerformed
}

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(addScholarForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(addScholarForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(addScholarForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(addScholarForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new addScholarForm().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel33;
    private javax.swing.JLabel jLabel34;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel20;
    private javax.swing.JPanel jPanel34;
    public javax.swing.JTextField sc_des;
    public javax.swing.JTextField sc_id;
    private javax.swing.JComboBox<String> scholarName;
    private javax.swing.JComboBox<String> scholarType;
    // End of variables declaration//GEN-END:variables
}
