/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package admin;

import config.dbconnector;
import javax.swing.JOptionPane;

/**
 *
 * @author Hariell
 */
public class addScholarForm extends javax.swing.JFrame {

    /**
     * Creates new form updateScholarForm
     */
    public static String name = "";
    public String ads = "";

    public addScholarForm() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel34 = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        scholarName = new javax.swing.JComboBox<>();
        jLabel10 = new javax.swing.JLabel();
        scholarType = new javax.swing.JComboBox<>();
        jButton3 = new javax.swing.JButton();
        jLabel18 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        sc_des = new javax.swing.JEditorPane();
        jButton4 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel34.setBackground(new java.awt.Color(255, 255, 255));
        jPanel34.setPreferredSize(new java.awt.Dimension(543, 594));
        jPanel34.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel6.setText("Scholarship name");
        jPanel34.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 60, -1, 20));

        scholarName.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "CHED\t", "UNIFAST", "WORKING" }));
        jPanel34.add(scholarName, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 80, 270, 40));

        jLabel10.setText("Scholarship type");
        jPanel34.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 120, 130, 33));

        scholarType.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Academic", "Government", " " }));
        jPanel34.add(scholarType, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 150, 270, 40));

        jButton3.setBackground(new java.awt.Color(221, 68, 112));
        jButton3.setForeground(new java.awt.Color(255, 255, 255));
        jButton3.setText("Save");
        jButton3.setBorderPainted(false);
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        jPanel34.add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 350, -1, 30));

        jLabel18.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel18.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel18.setText("ADD SCHOLARSHIP FORM");
        jPanel34.add(jLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 10, 500, 30));

        jScrollPane2.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Scholarship description", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 0, 12), new java.awt.Color(102, 102, 102))); // NOI18N

        sc_des.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        jScrollPane2.setViewportView(sc_des);

        jPanel34.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 210, 270, 120));

        jButton4.setText("Cancel");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        jPanel34.add(jButton4, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 350, -1, 30));

        getContentPane().add(jPanel34, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 500, 400));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        dbconnector dbc = new dbconnector();
        if (sc_des.getText().isEmpty()) {
            JOptionPane.showMessageDialog(null, " All Fields Require!");
        } else {
            dbc.insertData("INSERT INTO table_scholarship (scholarship_name,scholarship_type,scholarship_descrip,scholarship_status) " + "VALUES ("
                    + "'" + scholarName.getSelectedItem() + "',"
                    + " '" + scholarType.getSelectedItem() + "',"
                    + " '" + sc_des.getText() + "',"
                    + "'" + "Pending')");
            JOptionPane.showMessageDialog(null, "Save Successfully!");
            adminDashboard db = new adminDashboard();
            db.setVisible(true);
            this.dispose();
        }
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        this.dispose();
    }//GEN-LAST:event_jButton4ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(addScholarForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(addScholarForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(addScholarForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(addScholarForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new addScholarForm().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel34;
    public javax.swing.JScrollPane jScrollPane2;
    public javax.swing.JEditorPane sc_des;
    private javax.swing.JComboBox<String> scholarName;
    private javax.swing.JComboBox<String> scholarType;
    // End of variables declaration//GEN-END:variables
}
