/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package admin;

import config.dbconnector;
import java.awt.Image;
import java.awt.image.BufferedImage;
import java.io.File;
import java.io.IOException;
import java.nio.file.Files;
import java.nio.file.StandardCopyOption;
import javax.swing.ImageIcon;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.imageio.ImageIO;
import javax.swing.filechooser.FileNameExtensionFilter;

/**
 *
 * @author Hariell
 */
public class updateStudentForm extends javax.swing.JFrame {

    /**
     * Creates new form studentForm
     */
    File selectedFile;
    String fileName;
    public String update_id;

    public updateStudentForm() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel34 = new javax.swing.JPanel();
        save = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        lname = new javax.swing.JTextField();
        address = new javax.swing.JTextField();
        number = new javax.swing.JTextField();
        jLabel19 = new javax.swing.JLabel();
        up = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        display = new javax.swing.JLabel();
        fname = new javax.swing.JTextField();
        dob = new com.toedter.calendar.JDateChooser();
        jLabel11 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        email = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();
        program = new javax.swing.JComboBox<>();
        jLabel15 = new javax.swing.JLabel();
        gends = new javax.swing.JComboBox<>();
        year = new javax.swing.JComboBox<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel34.setBackground(new java.awt.Color(255, 255, 255));
        jPanel34.setPreferredSize(new java.awt.Dimension(543, 594));
        jPanel34.setLayout(null);

        save.setBackground(new java.awt.Color(221, 68, 112));
        save.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        save.setForeground(new java.awt.Color(255, 255, 255));
        save.setText("Save");
        save.setBorderPainted(false);
        save.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                saveActionPerformed(evt);
            }
        });
        jPanel34.add(save);
        save.setBounds(330, 460, 140, 40);

        jButton1.setText("Cancel");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel34.add(jButton1);
        jButton1.setBounds(180, 460, 140, 40);

        lname.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Last name", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 0, 12), new java.awt.Color(102, 102, 102))); // NOI18N
        jPanel34.add(lname);
        lname.setBounds(330, 90, 140, 50);

        address.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Address", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 0, 12), new java.awt.Color(102, 102, 102))); // NOI18N
        jPanel34.add(address);
        address.setBounds(180, 300, 290, 50);

        number.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Contact number", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 0, 12), new java.awt.Color(102, 102, 102))); // NOI18N
        jPanel34.add(number);
        number.setBounds(180, 250, 290, 50);

        jLabel19.setFont(new java.awt.Font("Segoe UI", 1, 15)); // NOI18N
        jLabel19.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel19.setText("ADD STUDENT FORM");
        jPanel34.add(jLabel19);
        jLabel19.setBounds(0, 30, 800, 21);

        up.setText("Import");
        up.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                upActionPerformed(evt);
            }
        });
        jPanel34.add(up);
        up.setBounds(570, 300, 150, 40);

        jLabel8.setForeground(new java.awt.Color(153, 153, 153));
        jLabel8.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel8.setText("2x2 profile picture");
        jPanel34.add(jLabel8);
        jLabel8.setBounds(570, 110, 150, 20);

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        jPanel1.add(display, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 150, 150));

        jPanel34.add(jPanel1);
        jPanel1.setBounds(570, 140, 150, 150);

        fname.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "First name", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 0, 12), new java.awt.Color(102, 102, 102))); // NOI18N
        jPanel34.add(fname);
        fname.setBounds(180, 90, 140, 50);

        dob.setBackground(new java.awt.Color(255, 255, 255));
        jPanel34.add(dob);
        dob.setBounds(180, 160, 140, 40);

        jLabel11.setForeground(new java.awt.Color(102, 102, 102));
        jLabel11.setText("Gender");
        jPanel34.add(jLabel11);
        jLabel11.setBounds(330, 140, 140, 20);

        jLabel13.setForeground(new java.awt.Color(102, 102, 102));
        jLabel13.setText("Date of birth");
        jPanel34.add(jLabel13);
        jLabel13.setBounds(180, 140, 140, 20);

        email.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Email", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 0, 12), new java.awt.Color(102, 102, 102))); // NOI18N
        jPanel34.add(email);
        email.setBounds(180, 200, 290, 50);

        jLabel14.setForeground(new java.awt.Color(102, 102, 102));
        jLabel14.setText("Program");
        jPanel34.add(jLabel14);
        jLabel14.setBounds(180, 350, 140, 20);

        program.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "BSIT", "BSCRIM", "BSTM", "BSED" }));
        program.setOpaque(true);
        program.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                programActionPerformed(evt);
            }
        });
        jPanel34.add(program);
        program.setBounds(180, 370, 140, 40);

        jLabel15.setForeground(new java.awt.Color(102, 102, 102));
        jLabel15.setText("Year level");
        jPanel34.add(jLabel15);
        jLabel15.setBounds(330, 350, 140, 20);

        gends.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Male", "Female", "Other" }));
        gends.setOpaque(true);
        gends.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                gendsActionPerformed(evt);
            }
        });
        jPanel34.add(gends);
        gends.setBounds(330, 160, 140, 40);

        year.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "1st year", "2nd year", "3rd year", "4th year" }));
        year.setOpaque(true);
        year.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                yearActionPerformed(evt);
            }
        });
        jPanel34.add(year);
        year.setBounds(330, 370, 140, 40);

        getContentPane().add(jPanel34, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 800, 560));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void saveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_saveActionPerformed
        dbconnector dbc = new dbconnector();

        java.util.Date utilDate = dob.getDate();
        java.sql.Date sqlDate = new java.sql.Date(utilDate.getTime());

        if (fname.getText().isEmpty()
                || lname.getText().isEmpty()
                || email.getText().isEmpty()
                || gends.getSelectedItem() == null
                || dob.getDate() == null
                || address.getText().isEmpty()
                || number.getText().isEmpty()
                || program.getSelectedItem() == null
                || year.getSelectedItem() == null
                || selectedFile == null) {

            JOptionPane.showMessageDialog(null, "All fields including profile picture are required!");
            return;
        }

        if (utilDate == null) {
            JOptionPane.showMessageDialog(null, "Date of birth is required!");
            return;
        }

        fileName = selectedFile.getName();
        imagePath = "src/profile_picture/" + fileName;

        int num = dbc.updateData("UPDATE table_student "
                + "SET first_name = '" + fname.getText() + "',"
                + " last_name='" + lname.getText() + "',"
                + "email = '" + email.getText() + "', "
                + "gender ='" + gends.getSelectedItem() + "',"
                + "dob ='" + sqlDate + "',"
                + "address ='" + address.getText() + "',"
                + "phone_number ='" + number.getText() + "',"
                + "program ='" + program.getSelectedItem() + "',"
                + "year_level ='" + year.getSelectedItem() + "',"
                + "image ='" + imagePath + "',"
                + "status='" + "Active" + "' "
                + "WHERE student_id = '" + update_id + "'"
        );

        if (num == 0) {

        } else {
            JOptionPane.showMessageDialog(null, "Updated Successfully!");
            adminDashboard db = new adminDashboard();
            db.setVisible(true);
            this.dispose();
        }
    }//GEN-LAST:event_saveActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        this.dispose();
        fname.setText("");
        lname.setText("");
        email.setText("");
        gends.setSelectedIndex(-1);
        dob.setDate(null);
        address.setText("");
        number.setText("");
        program.setSelectedIndex(-1);
        year.setSelectedIndex(-1);
        selectedFile = null;
    }//GEN-LAST:event_jButton1ActionPerformed
    String imagePath;
    private void upActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_upActionPerformed
        JFileChooser fileChooser = new JFileChooser();
        FileNameExtensionFilter filter = new FileNameExtensionFilter("Image Files", "jpg", "jpeg", "png", "gif");
        fileChooser.setFileFilter(filter);

        int result = fileChooser.showOpenDialog(this);

        if (result == JFileChooser.APPROVE_OPTION) {
            selectedFile = fileChooser.getSelectedFile();

            try {
                BufferedImage originalImage = ImageIO.read(selectedFile);

                Image resizedImage = originalImage.getScaledInstance(160, 160, Image.SCALE_SMOOTH);
                ImageIcon icon = new ImageIcon(resizedImage);
                display.setIcon(icon);

                String imageName = selectedFile.getName();
                imagePath = "src/profile_picture/" + imageName;
                File destination = new File(imagePath);
                Files.copy(selectedFile.toPath(), destination.toPath(), StandardCopyOption.REPLACE_EXISTING);
                // Update the selectedFile to point to the new location
                selectedFile = destination;
            } catch (IOException e) {
                e.printStackTrace();
                JOptionPane.showMessageDialog(null, "Error reading image file: " + e.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
            }
        }
    }//GEN-LAST:event_upActionPerformed

    private void programActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_programActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_programActionPerformed

    private void gendsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_gendsActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_gendsActionPerformed

    private void yearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_yearActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_yearActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(updateStudentForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(updateStudentForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(updateStudentForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(updateStudentForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new updateStudentForm().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JTextField address;
    public javax.swing.JLabel display;
    public com.toedter.calendar.JDateChooser dob;
    public javax.swing.JTextField email;
    public javax.swing.JTextField fname;
    public javax.swing.JComboBox<String> gends;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel34;
    public javax.swing.JTextField lname;
    public javax.swing.JTextField number;
    public javax.swing.JComboBox<String> program;
    public javax.swing.JButton save;
    private javax.swing.JButton up;
    public javax.swing.JComboBox<String> year;
    // End of variables declaration//GEN-END:variables
}
