/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package admin;

import config.dbconnector;
import java.awt.Image;
import java.awt.image.BufferedImage;
import java.io.File;
import java.io.IOException;
import java.nio.file.Files;
import java.nio.file.StandardCopyOption;
import javax.imageio.ImageIO;
import javax.swing.Icon;
import javax.swing.ImageIcon;
import javax.swing.JFileChooser;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.filechooser.FileNameExtensionFilter;

/**
 *
 * @author Hariell
 */
public class updateStudentForm extends javax.swing.JFrame {

    File selectedFile;

    /**
     * Creates new form updateStudentForm
     */
    public updateStudentForm() {
        initComponents();
        if ("Male".equals(gender)) {
            female.setSelected(true);
            male.setSelected(false);
        } else {
            female.setSelected(false);
            male.setSelected(true);
        }
    }

    public static String gender;

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel34 = new javax.swing.JPanel();
        jPanel20 = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        gmail = new javax.swing.JTextField();
        fname = new javax.swing.JTextField();
        male = new javax.swing.JRadioButton();
        female = new javax.swing.JRadioButton();
        jLabel9 = new javax.swing.JLabel();
        status = new javax.swing.JComboBox<>();
        contact = new javax.swing.JTextField();
        course = new javax.swing.JTextField();
        jButton4 = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        display = new javax.swing.JLabel();
        up = new javax.swing.JButton();
        jLabel19 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel34.setBackground(new java.awt.Color(102, 102, 255));
        jPanel34.setPreferredSize(new java.awt.Dimension(543, 594));
        jPanel34.setLayout(null);

        jPanel20.setBackground(new java.awt.Color(255, 255, 255));
        jPanel20.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel8.setForeground(new java.awt.Color(153, 153, 153));
        jLabel8.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel8.setText("* Optional");
        jPanel20.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 310, 150, 20));

        gmail.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Gmail", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 0, 12), new java.awt.Color(102, 102, 102))); // NOI18N
        jPanel20.add(gmail, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 140, 290, 50));

        fname.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Name", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 0, 12), new java.awt.Color(102, 102, 102))); // NOI18N
        jPanel20.add(fname, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 90, 290, 50));

        male.setBackground(new java.awt.Color(255, 255, 255));
        male.setText("  Male");
        male.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                maleActionPerformed(evt);
            }
        });
        jPanel20.add(male, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 370, 81, 20));

        female.setBackground(new java.awt.Color(255, 255, 255));
        female.setText(" Female");
        female.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                femaleActionPerformed(evt);
            }
        });
        jPanel20.add(female, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 370, 90, 20));

        jLabel9.setForeground(new java.awt.Color(102, 102, 102));
        jLabel9.setText("Status");
        jPanel20.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 290, 60, 20));

        status.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Single\t", "Married", "Widowed", " " }));
        status.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                statusActionPerformed(evt);
            }
        });
        jPanel20.add(status, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 310, 290, 40));

        contact.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Contact number", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 0, 12), new java.awt.Color(102, 102, 102))); // NOI18N
        jPanel20.add(contact, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 190, 290, 50));

        course.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Course", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 0, 12), new java.awt.Color(102, 102, 102))); // NOI18N
        jPanel20.add(course, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 240, 290, 50));

        jButton4.setBackground(new java.awt.Color(221, 68, 112));
        jButton4.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jButton4.setForeground(new java.awt.Color(255, 255, 255));
        jButton4.setText("Save");
        jButton4.setBorderPainted(false);
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        jPanel20.add(jButton4, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 420, 140, 40));

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        jPanel1.add(display, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 150, 150));

        jPanel20.add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 100, 150, 150));

        up.setText("Import");
        up.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                upActionPerformed(evt);
            }
        });
        jPanel20.add(up, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 260, 150, 40));

        jLabel19.setFont(new java.awt.Font("Segoe UI", 1, 15)); // NOI18N
        jLabel19.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel19.setText("UPDATE STUDENT FORM");
        jPanel20.add(jLabel19, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 30, 800, -1));

        jLabel10.setText(" Gender");
        jPanel20.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 360, 70, 40));

        jButton1.setText("Cancel");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel20.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 420, 140, 40));

        jPanel34.add(jPanel20);
        jPanel20.setBounds(0, 0, 800, 500);

        getContentPane().add(jPanel34, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 800, 500));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents
    String fileName;
    public String update_id;

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        dbconnector dbc = new dbconnector();

        if (selectedFile != null) {
            fileName = selectedFile.getName();
            imagePath = "src/profile_picture/" + fileName;
        } else {
            String defaultImage = "src/profile_picture/default_profile.png";
            imagePath = defaultImage;
        }

        int num = dbc.updateData("UPDATE table_student "
                + "SET name = '" + fname.getText() + "',"
                + " gmail='" + gmail.getText() + "',"
                + "student_course = '" + course.getText() + "', "
                + "student_contactnum ='" + contact.getText() + "',"
                + "student_gender ='" + gender + "',"
                + "image ='" + imagePath + "',"
                + "student_status='" + status.getSelectedItem() + "' "
                + "WHERE student_id = '" + update_id + "'"
        );

        if (num == 0) {

        } else {
            JOptionPane.showMessageDialog(null, "Updated Successfully!");
            adminDashboard db = new adminDashboard();
            db.setVisible(true);
            this.dispose();
        }
    }//GEN-LAST:event_jButton4ActionPerformed

    private void statusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_statusActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_statusActionPerformed

    private void femaleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_femaleActionPerformed
        if (female.isSelected()) {
            male.setSelected(false);
            gender = "Female";
        }
    }//GEN-LAST:event_femaleActionPerformed

    private void maleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_maleActionPerformed
        if (male.isSelected()) {
            female.setSelected(false);
            gender = "Male";
        }
    }//GEN-LAST:event_maleActionPerformed

    String imagePath;

    private void upActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_upActionPerformed
        JFileChooser fileChooser = new JFileChooser();
        FileNameExtensionFilter filter = new FileNameExtensionFilter("Image Files", "jpg", "jpeg", "png", "gif");
        fileChooser.setFileFilter(filter);

        int result = fileChooser.showOpenDialog(this);

        if (result == JFileChooser.APPROVE_OPTION) {
            selectedFile = fileChooser.getSelectedFile();

            try {
                BufferedImage originalImage = ImageIO.read(selectedFile);

                Image resizedImage = originalImage.getScaledInstance(160, 160, Image.SCALE_SMOOTH);
                ImageIcon icon = new ImageIcon(resizedImage);
                display.setIcon(icon);

                String imageName = selectedFile.getName();
                imagePath = "src/profile_picture/" + imageName;
                File destination = new File(imagePath);
                Files.copy(selectedFile.toPath(), destination.toPath(), StandardCopyOption.REPLACE_EXISTING);
                // Update the selectedFile to point to the new location
                selectedFile = destination;
            } catch (IOException e) {
                e.printStackTrace();
                JOptionPane.showMessageDialog(null, "Error reading image file: " + e.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
            }
        }
    }//GEN-LAST:event_upActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        this.dispose();
        fname.setText("");
        gmail.setText("");
        course.setText("");
        contact.setText("");
        female.setSelected(false);
        male.setSelected(false);
        status.setSelectedIndex(0);
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;

                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(updateStudentForm.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);

        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(updateStudentForm.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);

        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(updateStudentForm.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);

        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(updateStudentForm.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new updateStudentForm().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JTextField contact;
    public javax.swing.JTextField course;
    public javax.swing.JLabel display;
    public javax.swing.JRadioButton female;
    public javax.swing.JTextField fname;
    public javax.swing.JTextField gmail;
    private javax.swing.JButton jButton1;
    public javax.swing.JButton jButton4;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel20;
    private javax.swing.JPanel jPanel34;
    public javax.swing.JRadioButton male;
    public javax.swing.JComboBox<String> status;
    private javax.swing.JButton up;
    // End of variables declaration//GEN-END:variables

    Icon ResizeImage(String string, Object object, JLabel images) {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }
}
